#!/bin/sh

openrc -U gui &

wlr-randr --output HDMI-A-1 --mode 3840x2160 --pos 0,1680 --transform normal --output DP-2 --mode 3840x2160 --pos 3840,0 --transform 270
swaybg -m fill -i $HOME/bg.jpg &

dbus-daemon --session --address=unix:path=$XDG_RUNTIME_DIR/bus &
imacros &
sfwbar &
mako &
