#!/bin/bash
set -e

# monitor
xinput map-to-output "$(xinput list | sed -nE '/2 Pen stylus/ s/.*id=([0-9]+).*/\1/p')" HDMI-0

# binds
xsetwacom set "Wacom Intuos PT S 2 Pad pad" Button 1 "key Ctrl Z"
xsetwacom set "Wacom Intuos PT S 2 Pad pad" Button 3 "key Delete"
xsetwacom set "Wacom Intuos PT S 2 Pad pad" Button 8 "key 1"
xsetwacom set "Wacom Intuos PT S 2 Pad pad" Button 9 "key 7"
